#!/bin/bash
rm -rf output
mkdir output
cp ./src/* ./output/
cd ./output/
javac --release 17 -encoding utf8 WebDAVParser.java
jar cfe WebDAVParser.jar WebDAVParser WebDAVParser.class
rm WebDAVParser.class WebDAVParser.java